#!/bin/sh

set -eu

exit_handler() {
   EXIT_CODE="$?"
   if [ "$EXIT_CODE" -eq 0 ]; then
     echo "All shells passed the tests!"
   else
     echo "Testing failed."
   fi
   return "$EXIT_CODE"
} 

trap exit_handler EXIT

docker_sh() {
   # Choose a small docker image with 'git' and a simple POSIX shell.
   docker run --rm \
      -v "$PWD":/upshell \
      alpine \
      sh -c 'apk add git > /dev/null 2>&1 && sh /upshell/'"$(printf %q "$1")"' sh'
}

for t in tests/*; do
   [ -e "$t" ] || break
   [ -x "$t" ] || continue
   ksh "$t" ksh
   bash "$t" bash
   zsh "$t" zsh
   dash "$t" dash
   docker_sh "$t"
done

