# bashrc - this is part of Upshell
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

[ "$PS1" ] || return

[ "$BASH" ] && UPSHELL_PHASE=pre-interactive.bash . ~/.upshell/dispatch
UPSHELL_PHASE=pre-interactive.sh . ~/.upshell/dispatch
[ "$BASH" ] && UPSHELL_PHASE=interactive.bash . ~/.upshell/dispatch
UPSHELL_PHASE=interactive.sh . ~/.upshell/dispatch

if [ -z "$UPSHELL_NO_ETC_BASHRC" ] && [ -r /etc/bashrc ] ; then
   . /etc/bashrc
fi

UPSHELL_PHASE=post-interactive.sh . ~/.upshell/dispatch
[ "$BASH" ] && UPSHELL_PHASE=post-interactive.bash . ~/.upshell/dispatch
